--[[
ä	\195\164	Jäger = J\195\164ger
Ä	\195\132	Ärger = \195\132rger
ö	\195\182	schön = sch\195\182n
Ö	\195\150	Ödipus = \195\150dipus
ü	\195\188	Rüstung = R\195\188stung
Ü	\195\156	Übung = \195\156bung
ß	\195\159	Straße = Stra\195\159e 
]]
local L = LibStub("AceLocale-3.0"):NewLocale("DocsUI_Nameplates", "deDE")
if not L then return end

-- Text
L["Close"] = "Schlie\195\159en"
L["coreDeleteMsg"] = "Falls du die eigenst\195\164ndige Version benutzt und gerade auf Version 3 upgraded hast, l\195\182sche bitte den DocsUI Ordner in \\World of Warcraft\\Interface\\Addons. Tu dies nicht, wenn du noch andere Addons von mir benutzt."
L["dummy"] = "attrappe"

-- Icons
do
L["Yellow Star"] = "Gelber Stern"
L["Orange Circle"] = "Oranger Kreis"
L["Purple Diamond"] = "Lila Diamant"
L["Green Triangle"] = "Gr\195\188nes Dreieck"
L["White Moon"] = "Wei\195\159er Mond"
L["Blue Square"] = "Blaues Quadrat"
L["Red X"] = "Rotes X"
L["White Skull"] = "Wei\195\159er Totenkopf"
end

-- Faction Champions
do
L["Shaabad"] = "Shaabad"
L["Saamul"] = "Saamul"
L["Broln Stouthorn"] = "Broln Starkhorn"
L["Thrakgar"] = "Thrakgar"
L["Velanaa"] = "Velanaa"
L["Baelnor Lightbearer"] = "Baelnor Lichttr\195\164ger"
L["Liandra Suncaller"] = "Liandra Sonnenrufer"
L["Malithas Brightblade"] = "Malithas Glanzklinge"
L["Kavina Grovesong"] = "Kavina Haineslied"
L["Melador Valestrider"] = "Melador Talwanderer"
L["Birana Stormhoof"] = "Birana Sturmhuf"
L["Erin Misthoof"] = "Erin Nebelhuf"
L["Anthar Forgemender"] = "Anthar Schmiedenformer"
L["Brienna Nightfell"] = "Brienna Tiefnacht"
L["Caiphus the Stern"] = "Caiphus der Ernste"
L["Vivienne Blackwhisper"] = "Vivienne Schwarzraunen"
L["Serissa Grimdabbler"] = "Serissa D\195\188sterhauch"
L["Harkzog"] = "Harkzog"
L["Shocuul"] = "Shocuul"
L["Narrhok Steelbreaker"] = "Narrhok Stahlbrecher"
L["Irieth Shadowstep"] = "Irieth Schattenschritt"
L["Maz'dinah"] = "Maz'dinah"
L["Tyrius Duskblade"] = "Tyrius D\195\164mmerklinge"
L["Gorgrim Shadowcleave"] = "Gorgrim Schattenspalter"
L["Alyssia Moonstalker"] = "Alyssia Mondpirscher"
L["Ruj'kah"] = "Ruj'kah"
L["Noozle Whizzlestick"] = "Noozle Zischelstock"
L["Ginselle Blightslinger"] = "Ginselle Seuchenwerfer"
end

-- Options -- St\195\164rkungszauber  Schw\195\164chungszauber
do
L["Level"] = "Level"
L["Social"] = "Social"
L["Class"] = "Klasse"
L["Role"] = "Rolle"
L["Debug"] = "Debug"
L["Width"] = "Breite"
L["Height"] = "H\195\182he"
L["Buffs"] = "St\195\164rkungszauber"
L["Totem"] = "Totem"
L["showLevel"] = "Zeige das Level."
L["socialIcon"] = "Zeige das Social Icon."
L["classIcon"] = "Zeige das Klasse Icon."
L["roleIcon"] = "Zeige das Rolle Icon."
L["debugMode"] = "Debugmodus."
L["Debug"] = "Debug"
L["Size"] = "Gr\195\182\195\159e"
L["Name"] = "Name"
L["Guild"] = "Gilde"
L["Friend"] = "Freund"
L["Enemy"] = "Feind"
L["PvE"] = "PvE"
L["PvP"] = "PvP"
L["healthBar"] = "Zeige das Leben f\195\188r diese Art von Einheit."
L["castBar"] = "Zeige den Zauberbalken f\195\188r diese Art von Einheit."
L["Enabled"] = "Aktiv"
L["Icon"] = "Icon"
L["Color"] = "Farbe"
L["Overlap"] = "\195\156berlappen"
L["allowOverlap"] = "Erlaube das \195\156berlappen von Namensplaketten."
L["visibilityTt"] = "Zeige Namensplaketten f\195\188r diese Art von Einheit."
L["Unit"] = "Einheit"
L["Pet"] = "Begleiter"
L["Guardian"] = "Besch\195\188tzer"
L["Totem"] = "Totem"
L["Number"] = "Anzahl"
L["buffsNumber"] = "Maximale Anzahl der sichtbaren St\195\164rkungszauber."
L["All my buffs"] = "Alle meine St\195\164rkungszauber"
L["All my debuffs"] = "Alle meine Schw\195\164chungszauber"
L["All any buffs"] = "Alle St\195\164rkungszauber"
L["All any debuffs"] = "Alle Schw\195\164chungszauber"
L["allMyBuffs"] = "Zeige alle St\195\164rkungszauber, die von mir gezaubert wurden."
L["allMyDebuffs"] = "Zeige alle Schw\195\164chungszauber, die von mir gezaubert wurden."
L["allAnyBuffs"] = "Zeige alle St\195\164rkungszauber.\nDies kann deine Performance verringern."
L["allAnyDebuffs"] = "Zeige alle Schw\195\164chungszauber.\nDies kann deine Performance verringern."
L["icon"] = "icon"
L["combat"] = "Kampf"
L["Config"] = "Konfiguration"
L["Arena"] = "Arena"
L["threatBar"] = "Zeige Bedrohung als Balken."
L["Bar"] = "Balken"
L["buffsTt"] = "Zeige St\195\164rkungszauber f\195\188r diese Art von Einheit."
L["Unknown"] = "Unbekannt"
L["unknownIcon"] = "Markiere unbekannte Einheiten mit einem blauen Icon."
L["Layout"] = "Layout"
L["Font"] = "Schriftart"
L["colorTt"] = "W\195\164hle die Farbe f\195\188r dieses Element."
L["Foreground"] = "Vordergrund"
L["Background"] = "Hintergrund"
L["Border"] = "Rand"
L["Threat"] = "Bedrohung"
L["safe"] = "sicher"
L["unsafe"] = "unsicher"
L["alert"] = "alarmierend"
L["Castbar"] = "Zauberbalken"
L["Visibility"] = "Sichtbarkeit"
L["Filter"] = "Filter"
L["Hider"] = "Ausblender"
L["Statusbar"] = "Statusbalken"
L["StatusbarTt"] = "W\195\164hle die Textur f\195\188r dieses Element."
L["fontTt"] = "W\195\164hle die Schriftart f\195\188r dieses Element."
L["Normal"] = "Normal"
L["Bold"] = "Fett"
L["Italic"] = "Kursiv"
L["Outline"] = "Umrandung"
L["None"] = "Keine"
L["Thin outline"] = "D\195\188nne Umrandung"
L["Thick outline"] = "Dicke Umrandung"
L["Scale"] = "Skalierung"
L["scale_tt"] = "W\195\164hle die Skalierung f\195\188r dieses Element."
L["size_tt"] = "W\195\164hle die Gr\195\182\195\159e f\195\188r dieses Element."
L["Presets"] = "Presets"
L["Blizzard"] = true
L["1 Pixel"] = true
L["Roth"] = true
L["Caith"] = true
L["Textures"] = "Texturen"
L["Miscellaneous"] = "Verschiedenes"
L["Combatlog fix"] = "Kampflog Fix"
L["combatLogFix"] = "Automatisch das Kampflog reparieren wenn es kaputt geht sowie beim Zonen."
L["Combatlog print"] = "Kampflog Ausgabe"
L["combatLogFixPrint"] = "Kampflog Reperaturen im Chat ausgeben."
L["Only my"] = "Nur meine"
L["filterOnlyMy"] = "Nur von mir gezaubert."
L["Buff"] = "St\195\164rkungszauber"
L["filterBuff"] = "Dies ist ein St\195\164rkungszauber."
L["Debuff"] = "Schw\195\164chungszauber"
L["filterDebuff"] = "Dies ist ein Schw\195\164chungszauber."
L["Never show"] = "Zeige niemals"
L["filterNeverShow"] = "Zeige diesen St\195\164rkungszauber/Schw\195\164chungszauber niemals."
L["High"] = "Hohe"
L["Medium"] = "Mittlere"
L["Low"] = "Niedrige"
L["priority"] = "Priorit\195\164t"
L["deleteTt"] = "L\195\182sche diesen St\195\164rkungszauber/Schw\195\164chungszauber."
L["Debuffs"] = "Schw\195\164chungszauber"
L["filterName"] = "Der Name des St\195\164rkungszaubers oder Schw\195\164chungszaubers den du hinzuf\195\188gen willst.\nEs muss der exakte Name sein."
L["priorityTt"] = "Die Priorit\195\164t dieses St\195\164rkungszaubers/Schw\195\164chungszaubers"
L["My"] = "Meine"
L["Any"] = "Alle"
L["hiderName"] = "Der Name des NPCs, den du ausblenden willst.\nEs muss der exakte Name sein."
L["Delete"] = "L\195\182schen"
L["hiderDeleteTt"] = "L\195\182sche diesen Ausblendereintrag."
L["Name replacer"] = "Namensersetzer"
L["Name,Replacement"] = "Name,Ersatz"
L["replacerName"] = "Der Name des NPCs, den du ersetzen willst.\nEs muss der exakte Name sein.\nTrenne mit einem Komma.\nBeispiel: Der Lichk\195\182nig,Herr Frost"
L["replacerDeleteTt"] = "L\195\182sche diesen Namensersetzereintrag."
L["Profiles"] = "Profile"
L["LFG"] = "LFG"
L["LFGName"] = "Ein Wort oder ein Satz, der das LFG Icon ausl\195\182st.\nGro\195\159-/Kleinschreibung ist egal."
L["LFGDeleteTt"] = "L\195\182sche diesen LFG-Eintrag."
L["lfgIcon"] = "Aktiviere das LFG Icon und den Text."
L["guildName"] = "Zeige den Gildennamen und die NPC Beschreibung."
L["Non-Targets"] = "Nicht-Ziele"
L["castBarNonTargets"] = "Zeige Zauberbalken auch für Namensplaketten, welche du nicht anvisiert hast.\nFunktioniert nur im Kampf und es hat einige Einschr\195\164nkungen."
L["tot"] = "Ziel-von-Ziel"
L["percent"] = "Prozent"
L["showHpPercent"] = "Zeige den Lebensbalkenwert prozentual an."
L["absolut"] = "Absolut"
L["showHpAbsolut"] = "Zeige den Lebensbalkenwert absolut an."
L["Healthbar"] = "Lebensbalken"
L["showHpBar"] = "Zeige einen Lebensbalken."
L["Custom"] = "Spezifisch"
L["threatEnabled"] = "Aktiviere die Bedrohungsanzeige und f\195\164rbe das Leben mit dem Bedrohungswert.\nSetze Maintanks in einem Schlachtzug, um getankte Feinde zu sehen.\Priorit\195\164t: Spezifisch > PvP > Klasse > Bedrohung"
L["healthBarColorCustom"] = "F\195\164rbe das Leben mit einer spezifischen Farbe.\nPriorit\195\164t: Spezifisch > PvP > Klasse > Bedrohung"
L["healthBarColorPvP"] = "F\195\164rbe das Leben mit der PvP-Team Farbe.\Priorit\195\164t: Spezifisch > PvP > Klasse > Bedrohung"
L["healthBarColorClass"] = "F\195\164rbe das Leben mit der Klassenfarbe.\nPriorit\195\164t: Spezifisch > PvP > Klasse > Bedrohung"
L["very safe"] = "sehr sicher"
L["tanked"] = "getankt"
L["I want a healthbar"] = "Ich m\195\182chte einen Lebensbalken haben"

end

--[[
ä	\195\164	Jäger = J\195\164ger
Ä	\195\132	Ärger = \195\132rger
ö	\195\182	schön = sch\195\182n
Ö	\195\150	Ödipus = \195\150dipus
ü	\195\188	Rüstung = R\195\188stung
Ü	\195\156	Übung = \195\156bung
ß	\195\159	Straße = Stra\195\159e 
]]