if GetLocale() == "frFR" then

function pslocalezone()
pszonecoliseum				= "L'épreuve du croisé"
pszoneulduar				= "Ulduar"
pszoneicecrowncit			= "Citadelle de la Couronne de glace"

end

function pslocale()

	psaddonmy = "Addon"
	psaddonoff = "Off"
	psaddonofmodno = "Addon désactivé - Ce module n'est pas chargé"
	psaddonok = "OK"
	psaddonon = "Addon activé"
	psaddonon2 = "ON"
	psaddonrepnoprom = "Annonce les alertes sans promotion" -- Needs review
	psaddonrepnoprom2 = "Maintenant vous pouvez annoncer toutes les alertes sans promotion" -- Needs review
	psaddonrepnoprom3 = "Maintenant vous devez être promu pour annoncer les alertes" -- Needs review
	psaddonrepon = "Activer les alertes dans le Tchat" -- Needs review
	psattack = "Chargé" -- Needs review
	-- psattackin = "Pull in"
	psattention = "Attention!"
	-- psautomarktxtinf = "You want to mark players but Boss Mods breaks your marks? Use this module! It will update marks if another addon will try to change them."
	-- psautomarnewinfo = "|cff00ff00NEW!|r Now you can set more than one nick for each mark (comma-separated), if first player dies or gone offline - mark will be updated on the next player in the list."
	-- psautomarnotu = "Mark {rt%s} |cffff0000will NOT|r be update!"
	psbuttonoff = "STOP"
	psbuttonon = "Départ" -- Needs review
	psbuttonreset = "Réinitialisé"
	pscanceled = "ANNULE!"
	pschataddbut = "Ajouter"
	pschataddfail = "Il n'y a pas de canaux à ajouter"
	pschataddsuc = "a été ajouté avec succès"
	pschataddtxtset1 = "Choisissez dans le menu ci dessous le canal de discussion que vous souhaitez  |cff00ff00add|r dans la liste" -- Needs review
	pschataddtxtset2 = "Il n'y a aucun canal à ajouter, essayez de le rejoindre: /join channel_name." -- Needs review
	pschatchopt = "Options des canaux de discussions"
	pschatlist1 = "raid"
	pschatlist2 = "alerte raid"
	pschatlist3 = "officier"
	pschatlist4 = "groupe"
	pschatlist5 = "guilde"
	pschatlist6 = "dit" -- Needs review
	pschatlist7 = "cri"
	pschatlist8 = "soi même"
	pschatmaxchan = "Vous ne pouvez ajouter plus de 5 canaux personnel" -- Needs review
	pschatnothadd = "Pas disponible sur ce canal"
	pschatopttitl = "Canaux de discussion: ajouter/ supprimer" -- Needs review
	pschatrembut = "Supprimer"
	pschatremfail = "Les canaux par défaut ne peuvent être supprimés"
	pschatremsuc = "a été supprimé avec succès"
	pschattitl2 = "Par défaut vous avez 8 canaux pour annoncer les informations, ici vous pouvez ajouter et supprimer des canaux personnel puis les choisir pour annoncer les informations dont vous avez besoin." -- Needs review
	pschetremtxt1 = "Choisissez dans le menu ci dessous le canal de discussion que vous voulez  |cffff0000remove|r de la liste (les canaux par defaut ne peuvent être supprimé)." -- Needs review
	pscolcast11 = "incante"
	pscolnewveranonce1 = "Le module a bien été mis à jour" -- Needs review
	pscolshieldannonce = "dans la fenêtre de discussion" -- Needs review
	pserror = "Erreur!"
	pserrorcantdo1 = "Impossible à faire! Tous les addons ont été désactivés, réactivez les et essayez à nouveau"
	pserrorcantdoanotherpullis = "Le pull-timer est déjà lancé par un autre addon !" -- Needs review
	pserrormenutimer1 = "Pour démarrer le Pull-timer, entrez une durée entre 2 et 20 sec." -- Needs review
	pserrormenutimer2 = "/fen pull 5, pour arrêter le pull-timer entrez /fen pull" -- Needs review
	pserrornotofficer = "Vous n'avez pas la permission d'utiliser cette fonction en raid. Demandez une promotion au Chef du Raid." -- Needs review
	psfneedrscaddon = "Pour ouvrir ce module vous devez installer l'addon 'RaidSlackCheck' "
	psfneedrscaddon2 = "L'addon montre qui utilise des potions en raid et signale qui n'en prend pas" -- Needs review
	psfneedrscaddonver11 = "Version 1.1 ou supérieur"
	psfnotofficerspam = "Vous n'avez aucun droit d'envoyer des alertes, mais elles sont activées dans l'addon" -- Needs review
	psfpotchecklocal = "Vérification des potions" -- Needs review
	psfpotchecklocal2 = "Vérification des potions" -- Needs review
	-- psfpotchecklocalt2 = "Flask check"
	-- psfpotchecklocalt3 = "Rebirth - Rebuff"
	psfserver = "ru-Gordunni"
	psiccnoloaderr2 = "Module \"Couronne de Glace\" est désactivé. Essayez à nouveau dans la Couronne de Glace." -- Needs review
	psleftmenu1 = "AddOn"
	psleftmenu2 = "Actualiser automatiquement les signes"
	psleftmenu3 = "Chronos"
	psleftmenu5 = "Ulduar"
	psleftmenu6 = "Colisé"
	psleftmenu7 = "Couronne de Glace"
	psmarkinfo1 = "A quelle fréquence mettre les marques à jour, sec.:" -- Needs review
	psmarkinfo2 = "Mettre à jour les marques pour:" -- Needs review
	-- psmarkinfo3 = "Autoupdate marks is enabled"
	-- psmarkinfo4 = "Autoupdate marks is disabled"
	-- psmarkofftxt = "Remove all marks"
	-- psmarkreflesh = "Autoupdate marks"
	psmarkrefleshoff = "désactivé"
	psmarkrefleshon = "activé"
	-- psmarks = "    Autoupdate marks on raid members"
	-- psmarkserror = "You have no rights to use marks in a raid, but module 'Autoupdate marks' is active!"
	-- psmin = "min."
	-- psminibuttset = "Show minimap button"
	-- psminut = "min."
	psmoduleload = "Module chargé:"
	psmodulenotload = "Erreur en chargeant le module:"
	psmoduletxtoff = "le module est désactivé"
	psmoduletxton = "le module est activé"
	psnewversfound = "Attention! Une nouvelle version de PhoenixStyle a été trouvée dans votre raid/guilde, il est recommandé de faire la mise à jour depuis curse.com ou wowinterface.com" -- Needs review
	psnewversfound2 = "Attention! Une nouvelle version de PhoenixStyle a été trouvée dans votre raid/guilde, votre version est très ancienne, il est fortement recommandé de faire la mise à jour depuis curse.com ou wowinterface.com" -- Needs review
	psnonickset = "Vous n'avez pas entrez de nom."
	psnopermissmark = "Vous n'avez pas de permission pour utiliser les marques dans un raid."
	psnotfoundinr = "non trouvé dans votre raid."
	psnotinraid = "Vous devez être dans un raid!"
	-- psoldvertxt = "(old version)"
	pspereriv = "Interrompu" -- Needs review
	pspereriv2 = "Interrompu" -- Needs review
	psraaddonanet = "Erreur! L'addon 'RaidAchievement' n'est pas installé"
	psraaddonanet2 = "Vous pouvez le télécharger sur curse.com ou wowinterface.com"
	psrscoldvers = "Vous avez une ancienne version de 'RaidSlackCheck. Il est conseillé de la mettre à jour."
	pssec = "sec."
	pssecund = "sec."
	pssend = "Envoyé(e)" -- Needs review
	pstimeerror1 = "Entrez un nombre entre 2 et 20 sec."
	pstimeerror2 = "Le timer de pause ne peut pas dépasser 30 min!" -- Needs review
	pstimeerror3 = "Le timer de pause de peut pas être inférieur à 30 sec!" -- Needs review
	pstimeerror4 = "Le timer ne peut pas dépasser 2 heures!" -- Needs review
	pstimeerror5 = "Un timer ne peut pas être inférieur à 10 sec!" -- Needs review
	pstimerbutton1 = "Démarrer le timer de pull" -- Needs review
	pstimerbutton2 = "Démarrer le timer de pause" -- Needs review
	pstimerbutton3 = "Démarrer votre timer perso" -- Needs review
	pstimernoname = "Non nommé" -- Needs review
	pstimers = "Timers" -- Needs review
	pstimersinfo1 = "Lorsque vous démarrez un timer, l'addon démarre un timer global dans les BossMods pour tous les membres du raid." -- Needs review
	pstimersinfo10 = "/fen attack5 (n'importe quel nombre entre 2 et 20 sec.)" -- Needs review
	pstimersinfo11 = "ou: entrer secondes pour le 'Pull' timer:" -- Needs review
	pstimersinfo12 = "Timer de Pause!" -- Needs review
	pstimersinfo13 = "entrer une durée pour le timer de 'Pause':" -- Needs review
	pstimersinfo14 = "Créer votre propre timer" -- Needs review
	pstimersinfo15 = "entrez un nom:"
	pstimersinfo16 = "durée:" -- Needs review
	pstimersinfo2 = "BossMods disponibles" -- Needs review
	pstimersinfo9 = "Pour le timer 'Pull' utilisez: /fen pull 5" -- Needs review
	pstimerstarts = "Le timer a commencé" -- Needs review
	pstwobm = "L'expiration du timer sera affiché par les timers de BigWigs, DBM, DXE et RaidWatch2." -- Needs review
	psuierror = "Erreur!" -- Needs review
	psuierroraddonoff = "Erreur! L'addon est désactivé - ce module n'a pas été chargé!" -- Needs review
	psuinomodule1 = "Erreur! Le module n'est pas installé!"
	psuinomodule2 = "Erreur! Le module que vous avez choisis n'est pas installé!"
	psulchatch = "Canal de discussion:"
	psulhp = "PV"
	psulonlyattheend = "- annonce uniquement après la fin du combat"
	psulonlyattheendstal = "- annonce uniquement si durée > 1 sec." -- Needs review
	psulsendto = "Envoyer au canal:"
	-- psulvkl = "on:"
	pswarnings = "annoncer avertissements"
	pswarningsoff = "désactivé"
	pswarningson = "activé"
	pswebsite = "www.blacklotus.ru"
	rscloccolor = "noms en couleurs" -- Needs review
	rsclocpot10 = "Qui utilisa"
	rsclocpot11 = "Qui n'utilisa pas"
	rsclocpot2 = "0 potion sélectionnée" -- Needs review
	-- rsclocrlslak = "report RL slack"


end

end